function y = sample_filter(x)
%SAMPLE_FILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.4 and the DSP System Toolbox 8.7.
% Generated on: 06-Mar-2015 12:49:09

persistent Hd;

if isempty(Hd)
    
    Fstop1 = 0.15;  % First Stopband Frequency
    Fpass1 = 0.25;  % First Passband Frequency
    Fpass2 = 0.95;  % Second Passband Frequency
    Fstop2 = 1.05;  % Second Stopband Frequency
    Astop1 = 60;    % First Stopband Attenuation (dB)
    Apass  = 1;     % Passband Ripple (dB)
    Astop2 = 60;    % Second Stopband Attenuation (dB)
    Fs     = 10;    % Sampling Frequency
    
    h = fdesign.bandpass('fst1,fp1,fp2,fst2,ast1,ap,ast2', Fstop1, Fpass1, ...
        Fpass2, Fstop2, Astop1, Apass, Astop2, Fs);
    
    Hd = design(h, 'butter', ...
        'MatchExactly', 'stopband', ...
        'SOSScaleNorm', 'Linf');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);


