function [times, offset] = get_referenced_time(now_time, offset)
% [times, offset] = get_referenced_time(now_times)
%
%   Returns a vector (times) of time in seconds.  The input should be a
%   vector of times generated by MATLAB's 'now' command.  offset is the
%   time in seconds since midnight on 1/1/2013 (can make this a param
%   later).  offset+times should provide the time in seconds since midnight
%   on 1/1/2013.

if nargin == 1
    offset = (now_time(1) - datenum([2013 1 1 0 0 0])) * 24*60*60;
end

times = now_time - now_time(1);
times = times * 24*60*60;