function stack = tiff_stack_from_files(directory, output_directory, varargin)
% stack = tiff_stack_from_files(format, output_directory)
%
%   Creates a tiff stack from a set of files. The order of files will be
%   the order generated by the dir command.


default_options = struct(...
    'c_idx', [], ...
    'loader', @(x) x ...
);
input_options = varargin2struct(varargin{:}); 
options = mergestruct(default_options, input_options);

all_files = dir(fullfile(directory, '*.tif'));

size_Z = length(all_files);

for i = 1:size_Z
    
    filename = fullfile(directory, all_files(i).name);
    im = load_tiff_stack(filename);
    
    if ~isempty(options.c_idx)
        im = squeeze(im(:,:,options.c_idx));
    elseif ndims(im) == 3
        im = squeeze(uint8(mean(im, 3)));
    end
    
    stack(:,:,i) = options.loader(im);
    
end

save_tiff_stack(stack, fullfile(output_directory, 'T_00001.tif'));