function times_from_matfile(input_file, varargin)
% times_from_matfile(input_file)
%   Takes a matfile with data field 'times' generated by the matlab 'now'
%   command and creates a structure:
%       offset: start time, in seconds from midnight on 1/1/2013
%       times: times, in seconds from start_time

[path, ~, ~] = fileparts(input_file);

default_options = struct(...
                    'output_directory', path ...
                    );
input_options = varargin2struct(varargin{:}); 
options = mergestruct(default_options, input_options);

F = matfile(input_file);

t = F.times;

% offset = (t(1) - datenum([2013 1 1 0 0 0])) * 24*60*60;
% 
% t = t - t(1); % subtract offset
% t = t * 24*60*60; % days to seconds

[t, offset] = get_referenced_time(t);

struct_to_save = struct('offset', offset, 'times', column(t));

output_file = fullfile(options.output_directory, 'times.json');

savejson('', struct_to_save, output_file);